import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {generateKeyPairSync} from 'node:crypto';
import {readInsights,reportingWindow} from '../functions/_lib/insights.js';
import {onRequestGet as overview} from '../functions/api/admin/overview.js';
import {onRequestPost as analytics,analyticsDay} from '../functions/api/analytics.js';
import {onRequestGet as publicReviews} from '../functions/api/reviews.js';
import {onRequestGet as listReviews,onRequestPost as moderate} from '../functions/api/admin/reviews.js';
import {onRequestPost as writeReview,onRequestDelete as deleteReview} from '../functions/api/account/review.js';
import {onRequestGet as payments} from '../functions/api/admin/payments/index.js';
const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync('migrations').sort())db.exec(fs.readFileSync(`migrations/${file}`,'utf8'));
let failBatch=false;
const D1={prepare(sql){let values=[];return {sql,bind(...params){values=params;return this;},async first(){return db.prepare(sql).get(...values)||null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){if(failBatch && sql.startsWith('INSERT INTO analytics_daily')){failBatch=false;throw new Error('D1 write interrupted');}const result=db.prepare(sql).run(...values);return {meta:{changes:Number(result.changes)}};}};},async batch(statements){db.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(/^SELECT/.test(statement.sql)?await statement.all():await statement.run());db.exec('COMMIT');return results;}catch(error){db.exec('ROLLBACK');throw error;}}};
let user={localId:'owner',email:'owner@example.invalid',emailVerified:true},published=true,owned=true,aggregateOffline=false;
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options={})=>{
 if(String(url).includes('accounts:lookup'))return Response.json({users:[user]});
 if(String(url).includes('oauth2.googleapis.com'))return Response.json({access_token:'test-access'});
 if(String(url).endsWith(':runAggregationQuery')){if(aggregateOffline)return Response.json({},{status:503});const where=JSON.parse(options.body).structuredAggregationQuery.structuredQuery.where;return Response.json([{result:{aggregateFields:{total:{integerValue:String(!where?42:where.fieldFilter.field.fieldPath==='status'?12:3)}}}}]);}
 if(String(url).includes('/documents/invitations/'))return Response.json({fields:{ownerUid:{stringValue:owned?'owner':'someone-else'},status:{stringValue:published?'published':'draft'}}});
 throw new Error('Unexpected test request');
};
const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const env={PAYMENTS_DB:D1,FIREBASE_WEB_API_KEY:'test',FIREBASE_PROJECT_ID:'demo-enveely',ADMIN_EMAILS:'admin@example.invalid',FIREBASE_SERVICE_ACCOUNT_EMAIL:'test@demo-enveely.iam.gserviceaccount.com',FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY:privateKey.export({type:'pkcs8',format:'pem'})};
const auth={authorization:'Bearer test','content-type':'application/json'};
const request=(path,payload,headers=auth)=>new Request(`https://test.invalid${path}`,{headers,...(payload!==undefined?{method:'POST',body:JSON.stringify(payload)}:{})});
const admin=()=>{user={localId:'admin',email:'admin@example.invalid',emailVerified:true};};const owner=()=>{user={localId:'owner',email:'owner@example.invalid',emailVerified:true};};
const now=new Date('2026-10-10T17:30:00Z'),window=reportingWindow(7,now);
const order=(id,status,reviewed,expiry='2027-01-01T00:00:00.000Z',invitation='inv_shared_12345')=>db.prepare('INSERT INTO payment_orders(id,uid,invitation_id,variant_id,duration_months,base_price,extension_fee,unique_code,expected_total,status,proof_key,created_at,updated_at,reviewed_at,expires_at,activation_started_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,'owner',invitation,'mayura-pearl',3,185000,0,111,185111,status,'',reviewed,reviewed,reviewed,expiry,'2026-10-10T16:00:00.000Z');
try{
 assert.equal(window.start,'2026-10-04T17:00:00.000Z');assert.equal(window.end,'2026-10-11T17:00:00.000Z');assert.equal(analyticsDay(now),'2026-10-11');
 order('pay_first_0001','active','2026-10-04T17:00:00.000Z','2026-10-05T00:00:00.000Z');
 order('pay_renew_0002','active','2026-10-09T17:30:00.000Z');order('pay_renew_0003','active','2026-10-10T01:00:00.000Z');
 order('pay_prior_0004','active','2026-10-04T16:59:59.000Z');order('pay_refund_0005','refunded','2026-10-09T17:30:00.000Z');order('pay_pending_0006','activation_pending','2026-10-09T17:30:00.000Z');order('pay_review_0007','pending_review','2026-10-09T17:30:00.000Z',undefined,'inv_review_12345');
 const data=await readInsights(env,7,now);assert.equal(data.summary.approved,3);assert.equal(data.summary.amount,185111*3);assert.equal(data.summary.packageSales,185000*3);assert.equal(data.summary.previousAmount,185111);assert.equal(data.summary.activePackages,1);assert.equal(data.summary.expiredOrders,1);assert.equal(data.summary.reviewPending,1);assert.equal(data.summary.activationPending,1);assert.equal(data.operations.staleActivations,1);assert.deepEqual(data.invitations,{total:42,published:12,recent:3});assert.equal(data.paymentTrend.find(row=>row.day==='2026-10-10').orders,2);assert.equal(data.summary.buyers,1);
 aggregateOffline=true;const outage=await readInsights(env,7,now);assert.deepEqual(outage.invitations,{total:null,published:null,recent:null});assert.equal(outage.summary.amount,data.summary.amount);assert.ok(outage.insights.some(row=>row.level==='warning'));aggregateOffline=false;
 assert.equal((await overview({request:request('/api/admin/overview',undefined,{}),env})).status,403);assert.equal((await overview({request:request('/api/admin/overview'),env})).status,403);admin();user.emailVerified=false;assert.equal((await overview({request:request('/api/admin/overview'),env})).status,403);admin();assert.equal((await overview({request:request('/api/admin/overview?days=8'),env})).status,400);assert.equal((await overview({request:request('/api/admin/overview?days=7'),env})).status,200);
 const event={consent:true,event:'template_preview',session:crypto.randomUUID(),eventId:crypto.randomUUID(),templateId:'mayura'};const eventRequest=body=>request('/api/analytics',body,{'content-type':'application/json',origin:'https://test.invalid','cf-connecting-ip':'192.0.2.15'});
 assert.equal((await analytics({request:request('/api/analytics',event),env})).status,403);assert.equal((await analytics({request:eventRequest({consent:false}),env})).status,204);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM analytics_events').get().n,0);assert.equal((await analytics({request:eventRequest({...event,email:'private@example.invalid'}),env})).status,400);
 assert.equal((await analytics({request:eventRequest(event),env})).status,204);assert.equal((await analytics({request:eventRequest(event),env})).status,204);assert.equal(db.prepare('SELECT count FROM analytics_daily').get().count,1);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM analytics_sessions').get().n,1);assert.match(db.prepare('SELECT visitor_hash FROM analytics_sessions').get().visitor_hash,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(db.prepare('SELECT * FROM request_limits').all()).includes('192.0.2.15'));
 failBatch=true;assert.equal((await analytics({request:eventRequest({...event,eventId:crypto.randomUUID()}),env})).status,503);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM analytics_events').get().n,1,'failed batch rolls back dedupe marker');assert.equal(db.prepare('SELECT count FROM analytics_daily').get().count,1);
 assert.equal((await analytics({request:eventRequest({...event,eventId:crypto.randomUUID()}),env})).status,204);assert.equal(db.prepare('SELECT count FROM analytics_daily').get().count,2);
 owner();const review={displayName:'Sari & Adi',message:'Mudah menyiapkan detail acara dari ponsel.',rating:5,publicConsent:true,invitationId:'inv_review_12345'};
 assert.equal((await writeReview({request:request('/api/account/review',review,{}),env})).status,401);published=false;assert.equal((await writeReview({request:request('/api/account/review',review),env})).status,403);published=true;owned=false;assert.equal((await writeReview({request:request('/api/account/review',review),env})).status,403);owned=true;user.emailVerified=false;assert.equal((await writeReview({request:request('/api/account/review',review),env})).status,403);owner();assert.equal((await writeReview({request:request('/api/account/review',{...review,publicConsent:false}),env})).status,400);assert.equal((await writeReview({request:request('/api/account/review',review),env})).status,200);
 assert.equal((await (await publicReviews({env})).json()).reviews.length,0);assert.equal((await moderate({request:request('/api/admin/reviews',{action:'add',...review,authentic:true}),env})).status,403);
 admin();const saved=db.prepare('SELECT * FROM customer_reviews').get();assert.equal((await moderate({request:request('/api/admin/reviews',{action:'approve',id:saved.id,updatedAt:saved.updated_at}),env})).status,200);const visible=(await (await publicReviews({env})).json()).reviews;assert.equal(visible.length,1);assert.deepEqual(Object.keys(visible[0]).sort(),['displayName','id','message','rating']);assert.equal((await moderate({request:request('/api/admin/reviews',{action:'hide',id:saved.id,updatedAt:'stale'}),env})).status,409);
 assert.equal((await moderate({request:request('/api/admin/reviews',{action:'add',...review,authentic:false}),env})).status,400);assert.equal((await moderate({request:request('/api/admin/reviews',{action:'add',...review,authentic:true}),env})).status,200);
 owner();assert.equal((await writeReview({request:request('/api/account/review',{...review,message:'Pratinjau dan isi acaranya bisa dicek bersama.'}),env})).status,200);assert.equal(db.prepare("SELECT status FROM customer_reviews WHERE uid='owner'").get().status,'pending');assert.equal((await (await publicReviews({env})).json()).reviews.length,1);assert.equal((await deleteReview({request:request('/api/account/review',undefined,auth),env})).status,200);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM customer_reviews WHERE uid='owner'").get().n,0);
 admin();for(let i=0;i<110;i++){order(`pay_history_${String(i).padStart(4,'0')}`,'rejected','2026-09-01T00:00:00.000Z',null,`inv_history_${i}`);db.prepare("INSERT INTO customer_reviews(id,display_name,rating,message,public_consent,status,created_at,updated_at) VALUES(?,?,5,?,1,'pending',?,?)").run(`review_history_${String(i).padStart(4,'0')}`,'Test user','A real test fixture, never a production review.','2026-09-01T00:00:00.000Z','2026-09-01T00:00:00.000Z');}
 const paginate=async(handler,path,key)=>{let cursor='',ids=[];do{const response=await handler({request:request(path+(cursor?`&cursor=${encodeURIComponent(cursor)}`:'')),env});assert.equal(response.status,200);const payload=await response.json();assert.ok(payload[key].length<=30);ids.push(...payload[key].map(row=>row.id));cursor=payload.cursor;}while(cursor);assert.equal(new Set(ids).size,ids.length);return ids;};assert.equal((await paginate(payments,'/api/admin/payments?status=rejected','orders')).length,110);assert.equal((await paginate(listReviews,'/api/admin/reviews?status=pending','reviews')).length,110);
 console.log('PASS: verified admin access, Jakarta period boundaries, real revenue/status/renewal counts, Firestore outage, opt-in analytics dedupe and atomic rollback, review ownership/consent/moderation/withdrawal, >100-record pagination.');
}finally{globalThis.fetch=originalFetch;db.close();}
