import assert from 'node:assert/strict';
import { templateVariants, resolveDesign } from '../src/data/variants.js';
import { sampleInvitation } from '../src/data/sample-invitation.js';
import { renderInvitation } from '../src/engine/renderer.js';
import { initInvitationMusic, stopInvitationMusic } from '../src/engine/music.js';
for (const variant of templateVariants) {
  const invitation = sampleInvitation(variant.parentTemplate, variant.id);
  const html = renderInvitation(invitation);
  assert.ok(html.includes(`inv--v-${variant.id}`));
  assert.ok(html.includes(({ amora: 'amora-scene', nusantara: 'nt-scene', lumiere: 'lm-scene', elysian: 'ey-scene', pusaka: 'pk-scene', mayura: 'my-scene', blocka: 'bk-scene', meadow: 'md-scene', serena: 'sr-scene' })[variant.parentTemplate] || 'atelier-art'));
  assert.ok(html.includes('data-rsvp-form'));
  assert.ok(!html.includes('undefined'));
  invitation._lite = true;
  assert.ok(!renderInvitation(invitation).includes('<iframe'));
}
assert.equal(resolveDesign('amora', 'elysian-noir').variantId, 'amora-garden');
globalThis.document = new EventTarget();
let frames = new Map(), id = 0;
globalThis.requestAnimationFrame = fn => { frames.set(++id, fn); return id; };
globalThis.cancelAnimationFrame = key => frames.delete(key);
const advance = (elapsed = 2000) => { const callbacks = [...frames.values()]; frames.clear(); callbacks.forEach(fn => fn(performance.now() + elapsed)); };
const audios = [];
globalThis.Audio = class extends EventTarget {
  constructor(src) { super(); this.src = src; this.volume = 1; this.paused = true; audios.push(this); }
  play() { this.paused = false; return Promise.resolve(); }
  pause() { this.paused = true; }
  removeAttribute() { this.src = ''; }
  load() {}
};
const button = new EventTarget();
button.attributes = {};
button.setAttribute = (k,v) => button.attributes[k] = v;
const icon = {};
const wrap = { dataset: { musicSrc:'local-test.mp3', musicVolume:'0.55' }, querySelector:s => s.includes('toggle') ? button : icon };
const root = new EventTarget();
root.querySelector = () => wrap;
initInvitationMusic(root);
const first = audios.at(-1);
assert.equal(first.paused, true, 'no playback before gesture');
button.dispatchEvent(new Event('click'));
await Promise.resolve();
assert.equal(first.volume, 0, 'fade starts silently');
advance();
assert.equal(first.volume, .55);
button.dispatchEvent(new Event('click'));
assert.equal(first.paused, false, 'pause waits for fade');
advance();
assert.equal(first.volume, 0);
assert.equal(first.paused, true);
wrap.dataset.musicVolume = '0';
initInvitationMusic(root);
assert.equal(first.src, '', 'old audio released');
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance();
assert.equal(audios.at(-1).volume, 0, 'zero volume preserved');

wrap.dataset.musicVolume = '0.55';
wrap.dataset.musicFadeIn = '2200';
wrap.dataset.musicFadeOut = '800';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(800);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Amora rises gradually');
advance(2500);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(300);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Amora fades before pausing');
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(2500);
assert.equal(audios.at(-1).paused, false, 'quick resume cancels pending pause');
assert.equal(audios.at(-1).volume, .55);
document.dispatchEvent(new Event('env:navigate'));
assert.equal(audios.at(-1).paused, true);
assert.equal(audios.at(-1).src, '', 'route cleanup uses document event');
assert.equal(frames.size, 0);
const nusantara = sampleInvitation('nusantara', 'nusantara-puspa');
nusantara.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const nusantaraHtml = renderInvitation(nusantara);
assert.ok(nusantaraHtml.includes('data-music-fade-in="2600"'));
assert.ok(nusantaraHtml.includes('data-music-fade-out="1100"'));
wrap.dataset.musicFadeIn = '2600';
wrap.dataset.musicFadeOut = '1100';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(1100);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Nusantara rises gradually');
advance(2800);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(400);
assert.equal(audios.at(-1).paused, false, 'Nusantara completes its fade before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(1300);
assert.equal(audios.at(-1).volume, 0);
assert.equal(audios.at(-1).paused, true);
const lumiere = sampleInvitation('lumiere', 'lumiere-gallery');
lumiere.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const lumiereHtml = renderInvitation(lumiere);
assert.ok(lumiereHtml.includes('data-music-fade-in="3000"'));
assert.ok(lumiereHtml.includes('data-music-fade-out="1200"'));
wrap.dataset.musicFadeIn = '3000';
wrap.dataset.musicFadeOut = '1200';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(1000);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Lumiere rises gradually');
advance(3300);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(500);
assert.equal(audios.at(-1).paused, false, 'Lumiere fades before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(1500);
assert.equal(audios.at(-1).paused, true);
assert.equal(audios.at(-1).volume, 0);
const elysian = sampleInvitation('elysian', 'elysian-ivory');
elysian.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const elysianHtml = renderInvitation(elysian);
assert.ok(elysianHtml.includes('data-music-fade-in="2400"'));
assert.ok(elysianHtml.includes('data-music-fade-out="1000"'));
wrap.dataset.musicFadeIn = '2400';
wrap.dataset.musicFadeOut = '1000';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(900);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Elysian rises gradually');
advance(2600);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(400);
assert.equal(audios.at(-1).paused, false, 'Elysian completes its fade before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(1200);
assert.equal(audios.at(-1).paused, true);
assert.equal(audios.at(-1).volume, 0);
stopInvitationMusic();
const pusaka = sampleInvitation('pusaka', 'pusaka-sogan');
pusaka.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const pusakaHtml = renderInvitation(pusaka);
assert.ok(pusakaHtml.includes('data-music-fade-in="2800"'));
assert.ok(pusakaHtml.includes('data-music-fade-out="1400"'));
assert.equal((pusakaHtml.match(/class="pk-scene /g) || []).length, (pusakaHtml.match(/data-section=/g) || []).length, 'every rendered section has cultural edge artwork');
const emptyPusaka = { ...pusaka, _draft: true, content: {}, sections: [{ id: 'story', enabled: true }] };
assert.ok(renderInvitation(emptyPusaka).includes('pk-scene'), 'empty editor sections retain their frame');
wrap.dataset.musicFadeIn = '2800';
wrap.dataset.musicFadeOut = '1400';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(900);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Pusaka rises gradually');
advance(3000);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(600);
assert.equal(audios.at(-1).paused, false, 'Pusaka fades before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(1600);
assert.equal(audios.at(-1).paused, true);
assert.equal(audios.at(-1).volume, 0);
stopInvitationMusic();
const mayura = sampleInvitation('mayura', 'mayura-jade');
mayura.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const mayuraHtml = renderInvitation(mayura);
assert.ok(mayuraHtml.includes('data-music-fade-in="3200"'));
assert.ok(mayuraHtml.includes('data-music-fade-out="1600"'));
assert.equal((mayuraHtml.match(/class="my-scene /g) || []).length, (mayuraHtml.match(/data-section=/g) || []).length, 'every Mayura section has garden artwork');
assert.ok(renderInvitation({ ...mayura, _draft:true, content:{}, sections:[{id:'story',enabled:true}] }).includes('my-scene'), 'empty Mayura editor section retains garden frame');
wrap.dataset.musicFadeIn = '3200';
wrap.dataset.musicFadeOut = '1600';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(1100);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Mayura rises gradually');
advance(3500);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(700);
assert.equal(audios.at(-1).paused, false, 'Mayura fades before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(1800);
assert.equal(audios.at(-1).paused, true);
assert.equal(audios.at(-1).volume, 0);
document.dispatchEvent(new Event('env:navigate'));
assert.equal(audios.at(-1).src, '');
assert.equal(frames.size, 0);
const blocka = sampleInvitation('blocka', 'blocka-sky-party');
blocka.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const blockaHtml = renderInvitation(blocka);
assert.ok(blockaHtml.includes('data-music-fade-in="2200"'));
assert.ok(blockaHtml.includes('data-music-fade-out="1400"'));
assert.equal((blockaHtml.match(/class="bk-scene /g) || []).length, (blockaHtml.match(/data-section=/g) || []).length, 'every Blocka section has world artwork');
assert.ok(renderInvitation({ ...blocka, _draft:true, content:{}, sections:[{id:'story',enabled:true}] }).includes('bk-scene'), 'empty Blocka editor section retains world frame');
wrap.dataset.musicFadeIn = '2200';
wrap.dataset.musicFadeOut = '1400';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(850);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Blocka rises gradually');
advance(2500);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(600);
assert.equal(audios.at(-1).paused, false, 'Blocka fades before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(1600);
assert.equal(audios.at(-1).paused, true);
assert.equal(audios.at(-1).volume, 0);
document.dispatchEvent(new Event('env:navigate'));
assert.equal(audios.at(-1).src, '');
assert.equal(frames.size, 0);
const meadow = sampleInvitation('meadow', 'meadow-picnic');
meadow.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const meadowHtml = renderInvitation(meadow);
assert.ok(meadowHtml.includes('data-music-fade-in="3000"'));
assert.ok(meadowHtml.includes('data-music-fade-out="1700"'));
assert.equal((meadowHtml.match(/class="md-scene /g) || []).length, (meadowHtml.match(/data-section=/g) || []).length, 'every Meadow section has woodland artwork');
assert.ok(renderInvitation({ ...meadow, _draft:true, content:{}, sections:[{id:'story',enabled:true}] }).includes('md-scene'), 'empty Meadow editor section retains woodland frame');
wrap.dataset.musicFadeIn = '3000';
wrap.dataset.musicFadeOut = '1700';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(1100);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Meadow rises gradually');
advance(3300);
assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(750);
assert.equal(audios.at(-1).paused, false, 'Meadow fades before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(1900);
assert.equal(audios.at(-1).paused, true);
assert.equal(audios.at(-1).volume, 0);
document.dispatchEvent(new Event('env:navigate'));
assert.equal(audios.at(-1).src, '');
assert.equal(frames.size, 0);
const serena = sampleInvitation('serena', 'serena-paper');
serena.content.musicSettings = { enabled: true, url: 'local-test.mp3' };
const serenaHtml = renderInvitation(serena);
assert.ok(serenaHtml.includes('data-music-fade-in="3200"'));
assert.ok(serenaHtml.includes('data-music-fade-out="1800"'));
assert.equal((serenaHtml.match(/class="sr-scene /g) || []).length, (serenaHtml.match(/data-section=/g) || []).length, 'every Serena section has a palace frame');
assert.ok(renderInvitation({ ...serena, _draft:true, content:{}, sections:[{id:'story',enabled:true}] }).includes('sr-scene'), 'empty Serena editor section retains palace frame');
wrap.dataset.musicFadeIn = '3200'; wrap.dataset.musicFadeOut = '1800';
initInvitationMusic(root);
button.dispatchEvent(new Event('click'));
await Promise.resolve(); advance(1200);
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55, 'Serena rises gradually');
advance(3500); assert.equal(audios.at(-1).volume, .55);
button.dispatchEvent(new Event('click')); advance(800);
assert.equal(audios.at(-1).paused, false, 'Serena fades before pausing');
assert.ok(audios.at(-1).volume > 0 && audios.at(-1).volume < .55);
advance(2000); assert.equal(audios.at(-1).paused, true); assert.equal(audios.at(-1).volume, 0);
document.dispatchEvent(new Event('env:navigate'));
assert.equal(audios.at(-1).src, ''); assert.equal(frames.size, 0);
console.log(`PASS: ${templateVariants.length} full/lite renders, family fallback, music fade/pause/zero-volume/route cleanup`);
