import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {generateKeyPairSync} from 'node:crypto';
import {onRequestPost as verify} from '../functions/api/payments/verify.js';
import {onRequestPost as review} from '../functions/api/admin/payments/[id]/review.js';
import {onRequestGet as list} from '../functions/api/payments/index.js';
import {calculatePackage} from '../src/data/plans.js';
import {isPaymentAdmin} from '../functions/_lib/firebase-admin.js';
const db=new DatabaseSync(':memory:');
db.exec(fs.readFileSync('migrations/0001_payments.sql','utf8'));db.exec(fs.readFileSync('migrations/0002_request_limits.sql','utf8'));
const D1={prepare(sql){let values=[];return {bind(...params){values=params;return this;},async first(){return db.prepare(sql).get(...values)||null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const result=db.prepare(sql).run(...values);return {meta:{changes:result.changes}};}};}};
const objects=new Map();let user={localId:'owner',email:'owner@example.invalid',emailVerified:true},variant='amora-garden';
const originalFetch=globalThis.fetch;
globalThis.fetch=async (url,options)=>{
  if(String(url).includes('accounts:lookup'))return Response.json({users:[user]});
  if(String(url).includes('/documents/invitations/'))return Response.json({fields:{ownerUid:{stringValue:'owner'},design:{mapValue:{fields:{variantId:{stringValue:variant}}}}}});
  if(String(url).includes('oauth2.googleapis.com'))return Response.json({access_token:'test-access'});
  if(String(url).includes('/documents/entitlements/'))return Response.json(JSON.parse(options.body));
  throw new Error('Unexpected test request');
};
const env={PAYMENTS_DB:D1,PAYMENT_PROOFS:{async put(key,value){objects.set(key,value)},async delete(key){objects.delete(key)}},FIREBASE_WEB_API_KEY:'test-key',FIREBASE_PROJECT_ID:'demo-enveely',ADMIN_EMAILS:'admin@example.invalid',AI:{async run(){return {response:JSON.stringify({amount:calculatePackage(variant,3).subtotal+111,paymentSuccessful:true,confidence:0.95,summary:'Matched'})};}}};
const request=()=>{const body=new FormData();Object.entries({orderId:'pay_test_12345678',invitationId:'inv_test_12345678',variantId:variant,durationMonths:'3',uniqueCode:'111'}).forEach(([k,v])=>body.set(k,v));body.set('proof',new File([new Uint8Array([255,216,255])],'test.jpg',{type:'image/jpeg'}));return new Request('https://test.invalid/api/payments/verify',{method:'POST',headers:{authorization:'Bearer test'},body});};
try {
  assert.equal(isPaymentAdmin({email:'admin@example.invalid',emailVerified:false},env),false);
  assert.equal((await verify({request:new Request('https://test.invalid',{method:'POST'}),env})).status,401);
  user={...user,localId:'other'};
  assert.equal((await verify({request:request(),env})).status,403);
  user={...user,localId:'owner'};
  const valid=await verify({request:request(),env});assert.equal(valid.status,200);assert.equal((await valid.json()).status,'ai_match');
  assert.equal(objects.size,1);
  assert.equal(db.prepare('SELECT expected_total FROM payment_orders').get().expected_total,calculatePackage(variant,3).subtotal+111);
  assert.equal((await verify({request:request(),env})).status,409);
  const remote=await list({request:new Request('https://test.invalid',{headers:{authorization:'Bearer test'}}),env});assert.equal((await remote.json()).orders.length,1);
  user={...user,localId:'other'};assert.equal((await (await list({request:new Request('https://test.invalid',{headers:{authorization:'Bearer test'}}),env})).json()).orders.length,0);
  user={...user,localId:'admin',email:'admin@example.invalid'};
  const adminRequest=decision=>new Request('https://test.invalid',{method:'POST',headers:{authorization:'Bearer test','content-type':'application/json'},body:JSON.stringify({decision})});
  assert.equal((await review({request:adminRequest('reject'),params:{id:'pay_test_12345678'},env})).status,200);
  assert.equal(db.prepare('SELECT status FROM payment_orders').get().status,'rejected');
  user={...user,localId:'owner',email:'owner@example.invalid'};
  env.AI.run=async()=>{throw new Error('AI temporarily unavailable')};
  assert.equal((await verify({request:request(),env})).status,200);
  assert.equal(db.prepare('SELECT status FROM payment_orders').get().status,'pending_review');
  user={...user,localId:'admin',email:'admin@example.invalid'};
  assert.equal((await review({request:adminRequest('approve'),params:{id:'pay_test_12345678'},env})).status,500);
  assert.equal(db.prepare('SELECT review_token FROM payment_orders').get().review_token,null);
  const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});
  env.FIREBASE_SERVICE_ACCOUNT_EMAIL='test@demo-enveely.iam.gserviceaccount.com';
  env.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY=privateKey.export({type:'pkcs8',format:'pem'});
  assert.equal((await review({request:adminRequest('approve'),params:{id:'pay_test_12345678'},env})).status,200);
  assert.equal(db.prepare('SELECT status FROM payment_orders').get().status,'active');
  assert.equal((await review({request:adminRequest('approve'),params:{id:'pay_test_12345678'},env})).status,409);
  console.log('PASS: payment ownership, totals, immutable order, account history, verified admin, rejection/resubmit, manual AI fallback, review lock recovery.');
}finally{globalThis.fetch=originalFetch;db.close();}
