import {getAuthToken} from '../services/auth.js';
import {listDrafts} from '../services/draft-store.js';
import {esc} from '../core/format.js';
import {icon} from '../core/icons.js';
import {toast,openModal} from './overlays.js';
export function reviewFormMarkup(){return `<article class="customer-review-panel" id="review"><header><div><h3>Bagaimana pengalamanmu?</h3><p>Ulasanmu membantu pengguna lain dan menjadi masukan untuk Enveely.</p></div>${icon('chat',{size:28})}</header><div data-review-form-host><p>Memuat ulasan akun…</p></div></article>`;}
export async function wireReviewForm(root,user){const host=root.querySelector('[data-review-form-host]');if(!host)return;let current=null;try{const token=await getAuthToken();const response=await fetch('/api/account/review',{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error();current=(await response.json()).review;}catch{if(host.isConnected)host.innerHTML='<p>Ulasan akun belum dapat dimuat. Buka kembali profil saat koneksi tersedia.</p>';return;}
 if(!host.isConnected)return;const drafts=listDrafts().filter(draft=>draft.status==='published');
 if(!user.emailVerified){host.innerHTML='<p>Verifikasi email untuk mengirim ulasan. Kamu bisa mengirim ulang tautan verifikasi dari informasi akun.</p>';return;}
 if(!drafts.length && !current){host.innerHTML='<p>Setelah undanganmu dipublikasikan, kamu bisa membagikan pengalaman di sini.</p>';return;}
 host.innerHTML=`${current?`<p class="review-status">${{pending:'Ulasanmu sedang menunggu persetujuan.',approved:'Ulasanmu sudah tampil di landing.',hidden:'Ulasanmu disimpan dan tidak tampil di landing.'}[current.status]}</p>`:''}<form data-customer-review><div class="review-form-grid"><label>Nama yang ditampilkan<input name="displayName" value="${esc(current?.displayName || user.displayName || '')}" required minlength="2" maxlength="80" autocomplete="name"></label><label>Penilaian<select name="rating">${[5,4,3,2,1].map(rating=>`<option value="${rating}" ${rating===(current?.rating || 5)?'selected':''}>${rating} dari 5</option>`).join('')}</select></label></div><label>Undangan<select name="invitationId" required>${drafts.map(draft=>`<option value="${esc(draft.id)}">${esc([draft.content?.groom?.nickname || draft.content?.groom?.name,draft.content?.bride?.nickname || draft.content?.bride?.name].filter(Boolean).join(' & ') || 'Undangan')}</option>`).join('')}</select></label><label>Ulasan<textarea name="message" required minlength="12" maxlength="1200" rows="4" placeholder="Ceritakan pengalaman menyiapkan undanganmu.">${esc(current?.message || '')}</textarea></label><label class="review-consent"><input type="checkbox" name="publicConsent" required> Saya mengizinkan nama tampilan dan ulasan ini ditampilkan publik setelah disetujui.</label><p data-review-error role="alert"></p><div class="review-form-actions"><button type="submit" class="btn btn--primary btn--sm">${current?'Perbarui ulasan':'Kirim ulasan'}</button>${current?'<button type="button" class="btn btn--ghost btn--sm" data-delete-review>Hapus ulasan</button>':''}</div></form>`;
 host.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,error=form.querySelector('[data-review-error]'),button=form.querySelector('[type="submit"]');if(!form.reportValidity())return;button.disabled=true;error.textContent='';const fields=new FormData(form);try{const token=await getAuthToken(),response=await fetch('/api/account/review',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({displayName:fields.get('displayName'),rating:Number(fields.get('rating')),invitationId:fields.get('invitationId'),message:fields.get('message'),publicConsent:fields.has('publicConsent')})}),payload=await response.json();if(!response.ok)throw new Error(payload.message);toast('Ulasan dikirim untuk diperiksa sebelum tampil.',{type:'success'});wireReviewForm(root,user);}catch(err){error.textContent=err.message || 'Ulasan belum dapat dikirim.';button.disabled=false;}});
 host.querySelector('[data-delete-review]')?.addEventListener('click',()=>openModal({title:'Hapus ulasanmu?',body:'<p>Ulasan ini akan dihapus dan berhenti tampil di landing.</p>',actions:[{label:'Batal'},{label:'Hapus',kind:'primary',onClick:async()=>{const token=await getAuthToken(),response=await fetch('/api/account/review',{method:'DELETE',headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Ulasan belum dapat dihapus.');toast('Ulasan dihapus.');wireReviewForm(root,user);}}]}));
 if(location.hash==='#review')root.querySelector('#review')?.scrollIntoView({block:'start',behavior:'instant'});
}
